name = "tjg-trestles-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "CACHE"
id = "da6e621a50564c73af834d3ccf3787af"

# Secrets are stored outside this file for security.
# Once you have your Trestles credentials, run:
#   npx wrangler secret put TRESTLES_CLIENT_ID
#   npx wrangler secret put TRESTLES_CLIENT_SECRET

[env.production]
name = "tjg-trestles-worker"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "da6e621a50564c73af834d3ccf3787af"

[env.development]
name = "tjg-trestles-worker-dev"
